import Head from 'next/head';
import type {ReactElement} from 'react';
import styled from '@emotion/styled';

const Container = styled.main`
  height: 100%;
  background-color: ${({theme}) => theme.bg.basic};

  display: flex;
  justify-content: center;
  align-items: center;
`;

export default function Home(): ReactElement {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <p>Hello next</p>
      </Container>
    </>
  );
}
